### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by VehementHam** [Biscuit-Colorscheme/biscuit#14]
I think that the README for the main buiscut  repo should have a wiki with pages for each port. The port repo `README`s should link to these pages. The wiki would be for instructions on how to enable the colorcheme. This feature is common among other colorschemes.

**Comment by tsukki9696** [comment]
I dont really maintain this anymore (as demand is nonexistent when it comes to this project, and I dont really like porting stuff that I wont use) but I can consider doing it one day, i'll close this issue and mention this same comment in the others, features can be requested but its highly unlikely that they'll be added.
