### ISSUE TITLE
Add My ST Patches to the Ports

### ISSUE THREAD

**Issue by VehementHam** [Biscuit-Colorscheme/biscuit#15]
I created ST ports:
* [biscuit-dark-6.4.diff](https://git.disroot.org/oink/biscuit-st/raw/branch/main/biscuit-dark-6.4.diff)
* [biscuit-light-6.4.diff](https://git.disroot.org/oink/biscuit-st/raw/branch/main/biscuit-light-6.4.diff)

**Comment by tsukki9696** [comment]
Same reply as in #14, I might make a separate repo for this one though
